### PR TITLE
Fix default repo permissions

### LINKED ISSUE #22: Repos where the user is not an owner return false positives from check added by Issue #18
**Describe the bug**
If the user is not an owner of the repo, they do no have permission to get the `default_repo_permission` and therefore it returns null. These two queries need to adjustment

query/organization/org_default_repo_permission_none_read.sql
query/organization/org_default_repo_permission_none.sql

**Steampipe version (`steampipe -v`)**
0.17.1

**Plugin version (`steampipe plugin list`)**
0.24.0

**To reproduce**
Run the query with access to a GH Org you are not an owner of

**Expected behavior**
These should report as Skipped

**Additional context**
PR forthcoming

### PR DESCRIPTION
**Pull request by jchrisfarris**
### Checklist
- [ ] Issue(s) linked

This PR closes #22

### CODE REVIEW

File: query/organization/org_default_repo_permission_none.sql [hunk 1]
```diff
@@ -2,10 +2,16 @@ select
   -- Required Columns
   html_url as resource,
   case
+    when default_repo_permission is null then 'skip'
```
Comment (cbruno10) [inline query/organization/org_default_repo_permission_none.sql:5]: @jchrisfarris Should it be `skip` or `info`? I think `info` is better, as that's a way to tell the user they need to manually verify somehow. Please see https://github.com/turbot/steampipe-mod-github-compliance/blob/67c01dddf393d263006a0ce4b235458be8aa45e5/query/organization/org_two_factor_required.sql as a reference.

File: query/organization/org_default_repo_permission_none.sql [hunk 2]
```diff
@@ -2,10 +2,16 @@ select
...
     when default_repo_permission = 'none' then 'ok'
     else 'alarm'
   end as status,
-  coalesce(name, login) || ' base permission is ' || default_repo_permission || '.' as reason,
+
```
Comment (cbruno10) [inline query/organization/org_default_repo_permission_none.sql:9]:
```suggestion
```

File: query/organization/org_default_repo_permission_none.sql [hunk 3]
```diff
@@ -2,10 +2,16 @@ select
...
+  case
+    when default_repo_permission is null then 'user is not an owner of this repo'
```
Comment (cbruno10) [inline query/organization/org_default_repo_permission_none.sql:11]: Can you please update the reason to be similar to https://github.com/turbot/steampipe-mod-github-compliance/blob/67c01dddf393d263006a0ce4b235458be8aa45e5/query/organization/org_two_factor_required.sql#L10?

File: query/organization/org_default_repo_permission_none.sql [hunk 4]
```diff
@@ -2,10 +2,16 @@ select
   -- Required Columns
   html_url as resource,
   case
+    when default_repo_permission is null then 'skip'
     when default_repo_permission = 'none' then 'ok'
     else 'alarm'
   end as status,
-  coalesce(name, login) || ' base permission is ' || default_repo_permission || '.' as reason,
+
+  case
```
Comment (cbruno10) [inline query/organization/org_default_repo_permission_none.sql:10]: I think we should keep the `coalesce(name, login)`, please see https://github.com/turbot/steampipe-mod-github-compliance/blob/67c01dddf393d263006a0ce4b235458be8aa45e5/query/organization/org_two_factor_required.sql#L9-L10 as a reference.

This is helpful as for users with multiple connections setup, we don't want the reasons to start with the same words/text each time, and putting the particular organization up front helps users figure out which row is for which connection quicker.

File: query/organization/org_default_repo_permission_none_read.sql [hunk 5]
```diff
@@ -2,11 +2,16 @@ select
   -- Required Columns
   html_url as resource,
   case
+    when default_repo_permission is null then 'skip'
```
Comment (cbruno10) [inline query/organization/org_default_repo_permission_none_read.sql:5]: Please see comments for the other query, I believe they should mostly be the same here as well.

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@jchrisfarris Please see review, thanks!

File: query/organization/org_default_repo_permission_none.sql (hunk 1 above)
Comment (jchrisfarris) [reply query/organization/org_default_repo_permission_none.sql:5]: If the user is not an owner, they cannot manually verify either. I chose skip because in these cases the user is not responsible for the GH Org.  

I can go with info is that is the convention.

**Review by cbruno10 — APPROVED** [review]
